# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import emails_pb2 as emails__pb2


class EmailsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTemplate = channel.unary_unary(
                '/emails.Emails/SendTemplate',
                request_serializer=emails__pb2.EmailTemplate.SerializeToString,
                response_deserializer=emails__pb2.EmailTemplate.FromString,
                )


class EmailsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmailsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTemplate,
                    request_deserializer=emails__pb2.EmailTemplate.FromString,
                    response_serializer=emails__pb2.EmailTemplate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emails.Emails', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Emails(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emails.Emails/SendTemplate',
            emails__pb2.EmailTemplate.SerializeToString,
            emails__pb2.EmailTemplate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
